project:
  type: book
  output-dir: docs

book:
  title: "Tutorial for ‘LaLonde (1986) after Nearly Four Decades: Lessons Learned’"
  chapters:
    - index.qmd
    - 01-Start.Rmd
    - 02-LDW.Rmd
    - 03-NSW.Rmd
    - 04-LCS.Rmd
    - 05-IRS.Rmd
    - references.Qmd
  repo-url: https://github.com/xuyiqing/lalonde
  repo-actions: [source, issue]
  repo-branch: main
  repo-subdir: tutorial
  sharing: [twitter, facebook]

bibliography: references.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools:
      source: repo
    code-link: true

execute: 
  cache: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 

editor: visual

